-- Create maintenance_logs table for tracking machine maintenance
CREATE TABLE public.maintenance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machine_id BIGINT NOT NULL REFERENCES public.assets(id) ON DELETE CASCADE,
    maintenance_type TEXT NOT NULL CHECK (maintenance_type IN ('scheduled', 'unscheduled', 'emergency')),
    reason TEXT NOT NULL,
    date_started TIMESTAMP WITH TIME ZONE NOT NULL,
    date_completed TIMESTAMP WITH TIME ZONE,
    machine_active_at_time BOOLEAN DEFAULT true,
    downtime NUMERIC,
    work_done TEXT NOT NULL,
    parts_replaced TEXT,
    technician TEXT NOT NULL,
    cost NUMERIC,
    location TEXT,
    remarks TEXT,
    service_reset BOOLEAN DEFAULT false,
    next_service_due TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create index for faster lookups
CREATE INDEX idx_maintenance_logs_machine_id ON public.maintenance_logs(machine_id);
CREATE INDEX idx_maintenance_logs_date_started ON public.maintenance_logs(date_started DESC);

-- Enable Row Level Security
ALTER TABLE public.maintenance_logs ENABLE ROW LEVEL SECURITY;

-- Create RLS policy for anonymous access (matching other tables)
CREATE POLICY "anon_maintenance_logs" ON public.maintenance_logs
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Create policy for authenticated users
CREATE POLICY "Allow authenticated users full access" ON public.maintenance_logs
    FOR ALL
    USING (auth.role() = 'authenticated'::text);